---
title: "git_00"
author: "Kristina Larson"
date: "Year 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!" 

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
How do I love thee? Let me count the ways.  
I love thee to the depth and breadth and height  
My soul can reach, when feeling out of sight  
For the ends of being and ideal grace.  
I love thee to the level of every day's  
Most quiet need, by sun and candlelight.  
I love thee freely, as men strive for right;  
I love thee purely, as they turn from Praise.  
I love with a passion put to use  
In my old griefs, and with my childhood's faith.  
I love thee with a love I seemed to lose  
With my lost saints, I love thee with the breath,  
Smiles, tears, of all my life! and, if God choose,  
I shall but love thee better after death.  


